### ISSUE TITLE
Can't import via Gradle into STS. Missing dependency commons.logging ?

### ISSUE THREAD

**Issue by kdvolder** [spring-guides/gs-accessing-data-gorm#4]
I get this error stopping me from import into STS. I also get the same error trying to build the project with gradle on commandline.

Same error on both initial and complete codesets. Output below:

kdvolder@bun3:~/git/gs-guides/gs-accessing-data-gorm/initial$ ./gradlew clean build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'initial'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find commons-logging:commons-logging:1.1.3.
     Required by:
         :initial:unspecified > org.springframework.boot:spring-boot-gradle-plugin:1.0.0.RC5 > org.springframework.boot:spring-boot-loader-tools:1.0.0.RC5 > org.springframework:spring-core:4.0.2.RELEASE

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by gregturn** [comment]
I don't see that error. Instead, I see the expected failure on "initial" because you can package up before you have a Main class. And "complete" builds fine.
