### ISSUE TITLE
Association methods not added to entities

### ISSUE THREAD

**Issue by scalding** [spring-guides/gs-accessing-data-gorm#5]
This is probably not the correct place for this; if it isn't a pointer would be appreciated.

When I use the GORM Boot plugin, the association methods (addTo*, removeFrom*, etc) are not added. If I add `HibernateUtils.enhanceSessionFactory(...)` to a post construct, the methods are available. It would be nice if these were available without having to do that (set up and configured in the plugin).

**Comment by gregturn** [comment]
I think this is an issue for Grails (https://grails.org/contribute.html#reporting-issues). I would suggest first scouting out the status of this plugin, which is only being demonstrated here. It's also possible to check on their Grails maling lists to see what their roadmap is in this arena.

Cheers!
